name: Extract Lessons

on:
  workflow_dispatch:
  push:
    paths:
      - 'extract_report.py'

jobs:
  extract:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests pdfplumber google-generativeai
      - name: Run script
        run: python -u extract_report.py
      - name: Commit JSON output
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add homework.json class_info_log.txt
          git commit -m "Update homework.json and log" || echo "No changes"
          git push
