```yaml
name: Extract Lessons

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdfplumber requests google-generativeai

    - name: Run extract_lessons.py
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python -u extract_lessons.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extract-output
        path: |
          homework.json
          class_info_log3.txt
        retention-days: 7

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add homework.json class_info_log3.txt
        git commit -m "Update homework.json and log"
        git pull --rebase
        git push
      continue-on-error: true  # Continue even if push fails
```

### Key Changes
1. **Script Changes**:
   - Added logging for the absolute paths of `homework.json` and `class_info_log3.txt` using `os.path.abspath`.
   - Added a message instructing you to download the files from GitHub Actions artifacts at `https://github.com/gx288/eng/actions` if running in a GitHub Action.

2. **Workflow Changes**:
   - Added an `upload-artifact` step to save `homework.json` and `class_info_log3.txt` as artifacts, with a 7-day retention period.
   - Set `continue-on-error: true` for the push step to ensure the workflow completes and uploads artifacts even if the push fails.

### Expected Output
The script will produce logs similar to the previous run, with additional messages for file locations:

```
[2025-10-17 23:13:00] INFO: Initializing script
[2025-10-17 23:13:00] INFO: Starting report extraction
[2025-10-17 23:13:00] INFO: Configured Gemini API
[2025-10-17 23:13:00] INFO: Found 32 URLs
[2025-10-17 23:13:00] INFO: Loaded 0 entries from homework.json
[2025-10-17 23:13:00] INFO: Processing URL: https://docs.google.com/document/d/14weW3ZfCAUceNLbb1rJinWaVk7h3DqaZ/edit
[2025-10-17 23:13:00] INFO: Processing report: https://docs.google.com/document/d/14weW3ZfCAUceNLbb1rJinWaVk7h3DqaZ/edit
[2025-10-17 23:13:00] INFO: PDF export URL: https://docs.google.com/document/d/14weW3ZfCAUceNLbb1rJinWaVk7h3DqaZ/export?format=pdf
[2025-10-17 23:13:01] INFO: Downloaded PDF to temp_report.pdf
[2025-10-17 23:13:01] INFO: Extracting text and links from PDF
[2025-10-17 23:13:01] INFO: Extracted 3805 characters and 8 links from PDF
[2025-10-17 23:13:01] INFO: Deleted PDF file: temp_report.pdf
[2025-10-17 23:13:01] INFO: Gemini API attempt 1/3
[2025-10-17 23:13:01] INFO: Selected model: models/gemini-2.5-flash-...
[2025-10-17 23:13:02] INFO: Processing API response
[2025-10-17 23:13:02] INFO: API attempt 1 successful
[2025-10-17 23:13:02] INFO: Processed report: https://docs.google.com/document/d/14weW3ZfCAUceNLbb1rJinWaVk7h3DqaZ/edit
[2025-10-17 23:13:02] INFO: Saved homework.json with 32 entries
[2025-10-17 23:13:02] INFO: Output files saved locally: /path/to/homework.json and /path/to/class_info_log3.txt
[2025-10-17 23:13:02] INFO: If running in GitHub Actions, download 'homework.json' and 'class_info_log3.txt' from the workflow artifacts at https://github.com/gx288/eng/actions
[2025-10-17 23:13:02] INFO: Script terminated
```

If the Git push fails, the workflow will still upload the artifacts, and you’ll see a similar error:

```
error: failed to push some refs to 'https://github.com/gx288/eng'
```

### How to Download the Files
1. **Locally**:
   - Check the log output for the absolute paths of `homework.json` and `class_info_log3.txt` (e.g., `/path/to/homework.json`).
   - Copy these files from your local machine or the GitHub Actions runner’s filesystem (if you have access).

2. **From GitHub Actions**:
   - Go to `https://github.com/gx288/eng/actions`.
   - Find the latest workflow run for the “Extract Lessons” job.
   - Scroll to the “Artifacts” section at the bottom of the run page.
   - Download the `extract-output` artifact, which contains `homework.json` and `class_info_log3.txt`.

### Recommendations
1. **Run Locally to Avoid Push Conflicts**:
   - If you’re running this in a local environment, use:
     ```bash
     python -u extract_lessons.py
     ```
   - Check the logs for the local file paths (e.g., `/path/to/homework.json`) and copy the files manually.

2. **Update the Workflow**:
   - Replace your existing `.github/workflows/extract.yml` with the provided workflow file.
   - Ensure `GEMINI_API_KEY` is set in your GitHub repository secrets (`Settings > Secrets and variables > Actions > New repository secret`).

3. **Resolve Git Conflicts (Optional)**:
   - To fix the push issue, pull the remote changes before pushing:
     ```bash
     git pull --rebase
     git push
     ```
   - Alternatively, force-push (if you’re sure you want to overwrite remote changes):
     ```bash
     git push --force
     ```
     **Warning**: Force-pushing will overwrite remote changes, so use with caution.

4. **Check Quota Limits**:
   - The script processed all URLs, but if you hit Gemini API quota limits in future runs (2 requests/minute in the free tier), reduce `link.txt` to 1-2 URLs or consider a paid plan (https://ai.google.dev/gemini-api/docs/rate-limits).

5. **Verify Dependencies**:
   - Ensure libraries are up to date:
     ```bash
     pip install --upgrade pdfplumber requests google-generativeai
     ```

Please update your script and workflow with the provided code, then run it again. Check the logs for the local file paths or visit `https://github.com/gx288/eng/actions` to download the artifacts. If you encounter issues or need help accessing the artifacts, share the new logs or let me know if you want a different method (e.g., saving to a local folder with a timestamped name).
