name: Kiem tra co report moi

on:
  schedule:
    - cron: '5 * * * *'  # Chạy mỗi giờ (UTC)
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  check-reports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager gspread oauth2client requests schedule pdfplumber google-generativeai python-telegram-bot==20.7

    - name: Create credentials.json
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > credentials.json

    - name: Run script
      env:
        NEW_CEC_USER: ${{ secrets.NEW_CEC_USER }}
        NEW_CEC_PASS: ${{ secrets.NEW_CEC_PASS }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_CHAT_ID_2: ${{ secrets.TELEGRAM_CHAT_ID_2 }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "Starting report checking..."
        python -u notimain.py  # Thay bằng tên file script thực tế nếu khác

    - name: Commit and push changes
      if: always()
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add processed2.json class_info_log2.txt vocab_total.json Report/* || true
        git commit -m "Update processed2.json, class_info_log2.txt, vocab_total.json, and Report/*" || echo "Nothing to commit"
        git push || echo "Nothing to push"
