name: Scrape Classes

on:
  schedule:
    - cron: '0 0 * * *'  # Hàng ngày lúc 00:00 UTC
  workflow_dispatch:  # Cho phép trigger manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Cần để push processed.json và logs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Write credentials
        run: echo "${{ secrets.CREDENTIALS_JSON }}" > credentials.json

      - name: Run script
        env:
          CEC_USERNAME: ${{ secrets.CEC_USERNAME }}
          CEC_PASSWORD: ${{ secrets.CEC_PASSWORD }}
        run: python -u main.py  # Thêm -u để unbuffer output

      - name: Commit and push changes
        if: always()  # Chạy kể cả khi job fail
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add processed.json class_info_log.txt
          git commit -m "Update processed.json and logs" || echo "No changes to commit"
          git push || echo "Push failed, likely no changes or already up-to-date"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: class_info_log.txt
