name: Kiem tra co report moi

on:
  schedule:
    - cron: '5 * * * *'  # Chạy mỗi giờ (UTC)
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  check-reports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client requests selenium webdriver-manager pdfplumber google-generativeai python-telegram-bot

    - name: Create credentials.json
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > credentials.json

    - name: Run script
      env:
        NEW_CEC_USER: ${{ secrets.NEW_CEC_USER }}
        NEW_CEC_PASS: ${{ secrets.NEW_CEC_PASS }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_CHAT_ID_2: ${{ secrets.TELEGRAM_CHAT_ID_2 }}
      run: |
        python -u notimain.py

    - name: Commit and push processed.json and log
      if: always()
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add processed.json class_info_log.txt
        git commit -m "Update processed.json and log" || echo "Nothing to commit"
        git push || echo "Nothing to push"
